# Generated by Django 4.2.25 on 2025-10-20 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bilimClassApp", "0002_school_subject_schoolclass_teacher_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата оценки")),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("lesson", "За урок"),
                            ("homework", "За домашнее задание"),
                            ("quarter", "За четверть"),
                            ("exam", "За экзамен"),
                        ],
                        default="lesson",
                        max_length=10,
                        verbose_name="Тип работы",
                    ),
                ),
                ("grade", models.CharField(max_length=10, verbose_name="Оценка")),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий учителя"),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bilimClassApp.schoolclass",
                        verbose_name="Класс",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "Ученик"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bilimClassApp.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bilimClassApp.teacher",
                        verbose_name="Учитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оценка",
                "verbose_name_plural": "Оценки",
                "ordering": ["-date", "student"],
            },
        ),
    ]
