# Generated by Django 4.2.25 on 2025-10-20 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bilimClassApp", "0003_assessment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="grade",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Оценка",
            ),
        ),
    ]
