# Generated by Django 4.2.25 on 2025-10-20 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bilimClassApp", "0004_alter_assessment_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Дата")),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Название праздника / причина"
                    ),
                ),
            ],
            options={
                "verbose_name": "Праздничный/Нерабочий день",
                "verbose_name_plural": "Праздничные/Нерабочие дни",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Отсутствовал по ув. причине"),
                            ("truant", "Прогул"),
                            ("late", "Опоздал"),
                        ],
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Комментарий (например, причина отсутствия)",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "Ученик"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись о посещаемости",
                "verbose_name_plural": "Журнал посещаемости",
                "ordering": ["-date", "student"],
                "unique_together": {("student", "date")},
            },
        ),
    ]
