# Generated by Django 4.2.25 on 2025-10-20 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bilimClassApp", "0005_holiday_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="was_absent",
            field=models.BooleanField(
                default=False, verbose_name="Пропустил урок (Н/Б)"
            ),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="grade",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Оценка",
            ),
        ),
    ]
