# Generated by Django 4.2.25 on 2025-10-20 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bilimClassApp", "0006_assessment_was_absent_alter_assessment_grade"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "ordering": ["-date", "lesson__start_time", "student"],
                "verbose_name": "Запись о посещаемости (поурочно)",
                "verbose_name_plural": "Журнал посещаемости (поурочно)",
            },
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="attendance",
            name="lesson",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="bilimClassApp.schedule",
                verbose_name="Урок по расписанию",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(verbose_name="Дата урока"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Присутствовал"),
                    ("valid", "Отсутствовал по ув. причине"),
                    ("truant", "Прогул"),
                    ("late", "Опоздал"),
                ],
                max_length=10,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("lesson", "date", "student")},
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="comment",
        ),
    ]
