# Generated by Django 4.2.25 on 2025-10-21 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bilimClassApp", "0007_alter_attendance_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "verbose_name": "Посещаемость",
                "verbose_name_plural": "Посещаемость",
            },
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="attendance",
            name="school_class",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="bilimClassApp.schoolclass",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attendance",
            name="subject",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="bilimClassApp.subject",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Присутствовал"),
                    ("A", "Отсутствовал"),
                    ("L", "Опоздал"),
                ],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "subject", "school_class", "date")},
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="lesson",
        ),
    ]
