# Generated by Django 4.2.25 on 2025-10-21 18:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bilimClassApp", "0008_alter_attendance_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Заголовок/Тема задания"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание задания")),
                (
                    "attached_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="homework_attachments/",
                        verbose_name="Прикрепленный файл",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("due_date", models.DateTimeField(verbose_name="Срок сдачи (дедлайн)")),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homeworks",
                        to="bilimClassApp.schoolclass",
                        verbose_name="Класс",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homeworks",
                        to="bilimClassApp.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_homeworks",
                        to="bilimClassApp.teacher",
                        verbose_name="Учитель (автор)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Домашнее задание",
                "verbose_name_plural": "Домашние задания",
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="HomeworkSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_text",
                    models.TextField(
                        blank=True, verbose_name="Текстовый ответ ученика"
                    ),
                ),
                (
                    "submission_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="submission_files/",
                        verbose_name="Прикрепленный файл ответа",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата сдачи"),
                ),
                (
                    "grade",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Оценка за работу",
                    ),
                ),
                (
                    "teacher_comment",
                    models.TextField(blank=True, verbose_name="Комментарий учителя"),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата проверки"
                    ),
                ),
                (
                    "homework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="bilimClassApp.homework",
                        verbose_name="Домашнее задание",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "Ученик"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на ДЗ",
                "verbose_name_plural": "Ответы на ДЗ",
                "ordering": ["-submitted_at"],
                "unique_together": {("homework", "student")},
            },
        ),
    ]
