# Generated by Django 4.2.25 on 2025-10-22 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bilimClassApp", "0009_homework_homeworksubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="submission",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bilimClassApp.homeworksubmission",
                verbose_name="Сданная работа",
            ),
        ),
        migrations.AlterField(
            model_name="homework",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homeworks_by_subject",
                to="bilimClassApp.subject",
                verbose_name="Предмет",
            ),
        ),
    ]
