# Generated by Django 4.2.25 on 2025-10-23 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bilimClassApp", "0011_user_alter_assessment_student_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="school",
        ),
        migrations.AlterField(
            model_name="assessment",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "Ученик"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ученик",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="homeworksubmission",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "Ученик"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homework_submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ученик",
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
