# Generated by Django 4.2.25 on 2025-10-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bilimClassApp", "0014_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("teacher", "Учитель"),
                    ("student", "Ученик"),
                    ("headteacher", "Завуч"),
                    ("admin", "Администратор"),
                ],
                max_length=20,
                null=True,
                verbose_name="Роль",
            ),
        ),
    ]
