# Generated by Django 4.2.25 on 2025-10-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bilimClassApp", "0015_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolclass",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bilimClassApp.teacher",
                verbose_name="Классный руководитель",
            ),
        ),
    ]
