# Generated by Django 4.2.25 on 2025-10-24 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bilimClassApp", "0016_schoolclass_class_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours_per_week",
                    models.PositiveSmallIntegerField(
                        blank=True, default=1, null=True, verbose_name="Часов в неделю"
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bilimClassApp.schoolclass",
                        verbose_name="Класс",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bilimClassApp.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bilimClassApp.teacher",
                        verbose_name="Учитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение учителя",
                "verbose_name_plural": "Назначения учителей",
                "ordering": ["teacher__user__last_name", "school_class__name"],
                "unique_together": {("teacher", "school_class", "subject")},
            },
        ),
    ]
