# Generated by Django 4.2.25 on 2025-10-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bilimClassApp", "0017_teacherassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название урока"),
                ),
                ("date", models.DateField(verbose_name="Дата проведения")),
                (
                    "topic",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Тема урока"
                    ),
                ),
                (
                    "goals_and_objectives",
                    models.TextField(blank=True, verbose_name="Цели и задачи урока"),
                ),
                (
                    "learning_materials",
                    models.TextField(blank=True, verbose_name="Учебные материалы"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("approved", "Утвержден"),
                            ("rejected", "Отклонен"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="bilimClassApp.schoolclass",
                        verbose_name="Класс",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="bilimClassApp.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_plans",
                        to="bilimClassApp.teacher",
                        verbose_name="Учитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поурочный план",
                "verbose_name_plural": "Поурочные планы",
                "ordering": ["-date", "school_class"],
            },
        ),
    ]
