# Generated by Django 4.2.25 on 2025-10-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bilimClassApp", "0018_lessonplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lessonplan",
            name="learning_materials",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="lesson_plan_materials/",
                verbose_name="Учебные материалы (файл)",
            ),
        ),
    ]
